name = "design-hub-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "design-hub"
database_id = "b785c9c7-15fb-4234-bf62-58f038b90775"

[triggers]
crons = ["0 13 * * 3,5"]
